#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Apr 15 20:59:40 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=ComplementaryReimagined_r5.6.1 + EuphoriaPatches_1.7.4
enableShaders=false
